### ISSUE TITLE
Cannot find module 'moment'

### ISSUE THREAD

**Issue by demsullivan** [bdvholmes/ember-time-input#1]
Hey, so I tried loading this up in my app but Ember complains about the 'moment' module being missing in the JS Console. I tried installing the moment package in both npm and bower, but the fact that it's looking for a 'module' suggests that it's actually an Ember thing it's looking for.

Any suggestions?

**Comment by bdvholmes** [comment]
Interesting. I'll have a look!

**Comment by demsullivan** [comment]
Actual error might be a little more helpful:

> Uncaught Error: Could not find module `moment` imported from `ember-time-input/components/time-input`

**Comment by bdvholmes** [comment]
Thanks. I should mention, currently this will output a moment style date. Are you using regular date objects?

**Comment by demsullivan** [comment]
I'm not using anything at the moment.. this is a brand new app I'm building and needed a formatted time input field, which led me to your component. I'm not picky about what kind of object it outputs, as long as I can serialize it and save it into an Ember model to ship off to the backend.

**Comment by bdvholmes** [comment]
Perfect. I'll look at getting this to work with a vanilla app, but probably won't have something for you until tomorrow.

If you want an immediate solution, this addon is working fine in my ember apps. They are using [ember-moment](https://github.com/stefanpenner/ember-moment) which imports `bower` through [ember-cli-moment-shim](https://github.com/jasonmit/ember-cli-moment-shim). Are you using ember-cli?

**Comment by bdvholmes** [comment]
Reproduced in https://github.com/bdvholmes/ember-time-input-example/commit/3ad95177de05c0c9dcadfeacb44babfc1711bfda

**Comment by bdvholmes** [comment]
Ok sorry about that, should be working now with [v0.0.6](https://github.com/bdvholmes/ember-time-input/releases/tag/v0.0.6). Be sure to run

```
ember g ember-time-input
```

Please don't hesitate to open other issues, I'd love to know how you get on :-)
